import { createHash } from 'node:crypto';

import type { RedisFunctionRegistry } from './function-registry.js';

export type RedisFunctionLibrary = {
  registry: RedisFunctionRegistry;
  source: string;
  contentHash: string;
};

function register(functionName: string, callback: string): string {
  return `redis.register_function{function_name='${functionName}', callback=${callback}}`;
}

export function buildFunctionLibrary(registry: RedisFunctionRegistry): RedisFunctionLibrary {
  const source = [
    `#!lua name=${registry.libraryName}`,
    'local function key_type(key)',
    "  local result = redis.call('TYPE', key)",
    "  if type(result) == 'table' then return result['ok'] end",
    '  return result',
    'end',
    'local function type_is(key, expected)',
    '  local actual = key_type(key)',
    "  return actual == 'none' or actual == expected",
    'end',
    'local function stream_appendable(key)',
    "  if key_type(key) == 'none' then return true end",
    "  local info = redis.call('XINFO', 'STREAM', key)",
    '  for index = 1, #info, 2 do',
    "    if info[index] == 'last-generated-id' then",
    "      return info[index + 1] ~= '18446744073709551615-18446744073709551615'",
    '    end',
    '  end',
    '  return false',
    'end',
    'local function redis_now()',
    "  local now = redis.call('TIME')",
    '  local seconds = tonumber(now[1])',
    '  local milliseconds = math.floor(tonumber(now[2]) / 1000)',
    '  local days = math.floor(seconds / 86400)',
    '  local seconds_of_day = seconds - (days * 86400)',
    '  local era = math.floor(days / 146097)',
    '  local day_of_era = days - (era * 146097) + 719468',
    '  era = math.floor(day_of_era / 146097)',
    '  day_of_era = day_of_era - (era * 146097)',
    '  local year_of_era = math.floor((day_of_era - math.floor(day_of_era / 1460) + math.floor(day_of_era / 36524) - math.floor(day_of_era / 146096)) / 365)',
    '  local year = year_of_era + (era * 400)',
    '  local day_of_year = day_of_era - ((365 * year_of_era) + math.floor(year_of_era / 4) - math.floor(year_of_era / 100))',
    '  local month_prime = math.floor(((5 * day_of_year) + 2) / 153)',
    '  local day = day_of_year - math.floor(((153 * month_prime) + 2) / 5) + 1',
    '  local month',
    '  if month_prime < 10 then month = month_prime + 3 else month = month_prime - 9 end',
    '  if month <= 2 then year = year + 1 end',
    '  local hour = math.floor(seconds_of_day / 3600)',
    '  local minute = math.floor((seconds_of_day % 3600) / 60)',
    '  local second = seconds_of_day % 60',
    "  return {timestamp=string.format('%04d-%02d-%02dT%02d:%02d:%02d.%03dZ', year, month, day, hour, minute, second, milliseconds), milliseconds=(seconds * 1000) + milliseconds}",
    'end',
    'local function iso_from_milliseconds(epoch_milliseconds)',
    '  local seconds = math.floor(epoch_milliseconds / 1000)',
    '  local milliseconds = epoch_milliseconds - (seconds * 1000)',
    '  local days = math.floor(seconds / 86400)',
    '  local seconds_of_day = seconds - (days * 86400)',
    '  local era = math.floor(days / 146097)',
    '  local day_of_era = days - (era * 146097) + 719468',
    '  era = math.floor(day_of_era / 146097)',
    '  day_of_era = day_of_era - (era * 146097)',
    '  local year_of_era = math.floor((day_of_era - math.floor(day_of_era / 1460) + math.floor(day_of_era / 36524) - math.floor(day_of_era / 146096)) / 365)',
    '  local year = year_of_era + (era * 400)',
    '  local day_of_year = day_of_era - ((365 * year_of_era) + math.floor(year_of_era / 4) - math.floor(year_of_era / 100))',
    '  local month_prime = math.floor(((5 * day_of_year) + 2) / 153)',
    '  local day = day_of_year - math.floor(((153 * month_prime) + 2) / 5) + 1',
    '  local month',
    '  if month_prime < 10 then month = month_prime + 3 else month = month_prime - 9 end',
    '  if month <= 2 then year = year + 1 end',
    '  local hour = math.floor(seconds_of_day / 3600)',
    '  local minute = math.floor((seconds_of_day % 3600) / 60)',
    '  local second = seconds_of_day % 60',
    "  return string.format('%04d-%02d-%02dT%02d:%02d:%02d.%03dZ', year, month, day, hour, minute, second, milliseconds)",
    'end',
    'local function append_event(global_stream, project_stream, event_json)',
    "  local global_stream_id = redis.call('XADD', global_stream, '*', 'event', event_json)",
    "  local project_stream_id = redis.call('XADD', project_stream, '*', 'event', event_json)",
    '  return {globalStreamId=global_stream_id, projectStreamId=project_stream_id}',
    'end',
    'local function project_register(keys, args)',
    '  if #keys ~= 5 or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local decoded, project = pcall(cjson.decode, args[1])',
    "  if not decoded or type(project) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local required = {'id', 'name', 'localPath', 'canonicalPath', 'identityPath', 'pathIdentityHash'}",
    '  for _, field in ipairs(required) do',
    "    if type(project[field]) ~= 'string' or project[field] == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    "  if type(args[2]) ~= 'string' or args[2] == '' or type(args[3]) ~= 'string' or args[3] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'set') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then",
    "    return cjson.encode({status='error', code='PROJECT_ID_CONFLICT'})",
    '  end',
    "  local existing_identity = redis.call('GET', keys[2])",
    '  if existing_identity then',
    '    local valid, existing = pcall(cjson.decode, existing_identity)',
    "    if not valid or type(existing) ~= 'table' or type(existing.projectId) ~= 'string' or type(existing.identityPath) ~= 'string' or type(existing.canonicalPath) ~= 'string' then",
    "      return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '    end',
    '    if existing.identityPath == project.identityPath then',
    "      return cjson.encode({status='conflict', reason='duplicate', existingProjectId=existing.projectId, canonicalPath=existing.canonicalPath})",
    '    end',
    "    return cjson.encode({status='conflict', reason='hash_collision'})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local timestamp = redis_now().timestamp',
    '  local stored = {',
    '    id=project.id, name=project.name, localPath=project.localPath,',
    '    canonicalPath=project.canonicalPath, createdAt=timestamp, updatedAt=timestamp',
    '  }',
    "  if type(project.repositoryUrl) == 'string' then stored.repositoryUrl = project.repositoryUrl end",
    "  if type(project.defaultBranch) == 'string' then stored.defaultBranch = project.defaultBranch end",
    '  local event = {',
    "    id=args[3], version=1, type='project.registered', occurredAt=timestamp,",
    '    workspaceId=args[2], projectId=project.id, payload={project=stored}',
    '  }',
    '  local event_json = cjson.encode(event)',
    "  redis.call('HSET', keys[1], 'id', stored.id, 'name', stored.name, 'localPath', stored.localPath, 'canonicalPath', stored.canonicalPath, 'identityPath', project.identityPath, 'pathIdentityHash', project.pathIdentityHash, 'createdAt', stored.createdAt, 'updatedAt', stored.updatedAt)",
    "  if stored.repositoryUrl then redis.call('HSET', keys[1], 'repositoryUrl', stored.repositoryUrl) end",
    "  if stored.defaultBranch then redis.call('HSET', keys[1], 'defaultBranch', stored.defaultBranch) end",
    "  redis.call('SET', keys[2], cjson.encode({projectId=project.id, identityPath=project.identityPath, canonicalPath=project.canonicalPath}))",
    "  redis.call('SADD', keys[3], project.id)",
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='created', project=stored, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_register(keys, args)',
    '  if #keys ~= 9 or #args ~= 5 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local decoded, session = pcall(cjson.decode, args[1])',
    "  if not decoded or type(session) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local required = {'id', 'agentId', 'projectId', 'status', 'workingDirectory', 'metadataJson'}",
    '  for _, field in ipairs(required) do',
    "    if type(session[field]) ~= 'string' or session[field] == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    "  if session.status ~= 'starting' or type(args[2]) ~= 'string' or args[2] == '' or type(args[3]) ~= 'string' or args[3] == '' or type(args[5]) ~= 'string' or args[5] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local ttl = tonumber(args[4])',
    '  if not ttl or ttl < 1 or ttl ~= math.floor(ttl) then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local metadata_valid, metadata = pcall(cjson.decode, session.metadataJson)',
    "  if not metadata_valid or type(metadata) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'set') or not type_is(keys[5], 'string') or not type_is(keys[6], 'zset') or not type_is(keys[7], 'stream') or not type_is(keys[8], 'stream') or not type_is(keys[9], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then",
    "    return cjson.encode({status='error', code='SESSION_ID_CONFLICT'})",
    '  end',
    "  if key_type(keys[2]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='project'})",
    '  end',
    "  local stored_project_id = redis.call('HGET', keys[2], 'id')",
    '  if stored_project_id ~= session.projectId then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[7]) or not stream_appendable(keys[8]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    '  local stored = {',
    "    id=session.id, agentId=session.agentId, projectId=session.projectId, status='starting',",
    '    workingDirectory=session.workingDirectory, startedAt=clock.timestamp,',
    '    lastHeartbeatAt=clock.timestamp, metadata=metadata',
    '  }',
    "  if type(session.taskSummary) == 'string' then stored.taskSummary = session.taskSummary end",
    "  if type(session.branch) == 'string' then stored.branch = session.branch end",
    "  if type(session.worktreePath) == 'string' then stored.worktreePath = session.worktreePath end",
    '  local event = {',
    "    id=args[3], version=1, type='session.registered', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=session.projectId, agentId=session.agentId,',
    '    sessionId=session.id, payload={session=stored}',
    '  }',
    '  local event_json = cjson.encode(event)',
    "  local group_ok, group_result = pcall(redis.call, 'XGROUP', 'CREATE', keys[9], args[5], '0-0', 'MKSTREAM')",
    "  if not group_ok and not string.find(tostring(group_result), 'BUSYGROUP') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', stored.id, 'agentId', stored.agentId, 'projectId', stored.projectId, 'status', stored.status, 'workingDirectory', stored.workingDirectory, 'startedAt', stored.startedAt, 'lastHeartbeatAt', stored.lastHeartbeatAt, 'metadata', session.metadataJson)",
    "  if stored.taskSummary then redis.call('HSET', keys[1], 'taskSummary', stored.taskSummary) end",
    "  if stored.branch then redis.call('HSET', keys[1], 'branch', stored.branch) end",
    "  if stored.worktreePath then redis.call('HSET', keys[1], 'worktreePath', stored.worktreePath) end",
    "  redis.call('SADD', keys[3], session.id)",
    "  redis.call('SADD', keys[4], session.id)",
    "  redis.call('SET', keys[5], session.id, 'PX', ttl)",
    "  redis.call('ZADD', keys[6], clock.milliseconds + ttl, session.id)",
    '  local streams = append_event(keys[7], keys[8], event_json)',
    "  return cjson.encode({status='created', session=stored, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_status(keys, args)',
    '  if #keys ~= 5 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local target = args[1]',
    '  local allowed = {idle=true, thinking=true, tool_running=true, waiting_for_input=true, waiting_for_agent=true, blocked=true, completed=true}',
    '  if not allowed[target] or args[2] == "" or args[3] == "" or args[4] == "" then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[2] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local current = values[4]',
    '  if current == target then',
    "    return cjson.encode({status='unchanged', currentStatus=current})",
    '  end',
    "  if current == 'completed' or current == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus=current})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', target)",
    "  if target == 'completed' then",
    "    redis.call('DEL', keys[2])",
    "    redis.call('ZREM', keys[3], values[1])",
    '  end',
    '  local event = {',
    "    id=args[4], version=1, type='session.status.changed', occurredAt=clock.timestamp,",
    '    workspaceId=args[3], projectId=values[3], agentId=values[2], sessionId=values[1],',
    '    payload={previousStatus=current, currentStatus=target}',
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='updated', previousStatus=current, currentStatus=target, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_heartbeat(keys, args)',
    '  if #keys ~= 5 or #args ~= 7 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local ttl = tonumber(args[4])',
    '  local interval = tonumber(args[5])',
    "  if args[1] == '' or args[2] == '' or args[3] == '' or not ttl or ttl < 1 or ttl ~= math.floor(ttl) or not interval or interval < 0 or interval ~= math.floor(interval) or (args[6] ~= '0' and args[6] ~= '1') then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status', 'metadata', 'lastHeartbeatEventAt')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or not values[5] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if values[4] == 'completed' or values[4] == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus=values[4]})",
    '  end',
    '  local metadata_changed = false',
    "  if args[6] == '1' then",
    '    local valid_metadata, decoded_metadata = pcall(cjson.decode, args[7])',
    "    if not valid_metadata or type(decoded_metadata) ~= 'table' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '    metadata_changed = values[5] ~= args[7]',
    '  end',
    '  local clock = redis_now()',
    '  local last_event_ms = tonumber(values[6])',
    '  local emit_event = not last_event_ms or (clock.milliseconds - last_event_ms) >= interval or metadata_changed',
    '  if emit_event and (not stream_appendable(keys[4]) or not stream_appendable(keys[5])) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'lastHeartbeatAt', clock.timestamp)",
    "  if args[6] == '1' then redis.call('HSET', keys[1], 'metadata', args[7]) end",
    "  redis.call('SET', keys[2], values[1], 'PX', ttl)",
    "  redis.call('ZADD', keys[3], clock.milliseconds + ttl, values[1])",
    '  if not emit_event then',
    "    return cjson.encode({status='renewed', eventEmitted=false, lastHeartbeatAt=clock.timestamp})",
    '  end',
    "  redis.call('HSET', keys[1], 'lastHeartbeatEventAt', clock.milliseconds)",
    '  local event = {',
    "    id=args[3], version=1, type='session.heartbeat', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    '    payload={metadataChanged=metadata_changed}',
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='renewed', eventEmitted=true, lastHeartbeatAt=clock.timestamp, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_close(keys, args)',
    '  if #keys ~= 5 or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    "  if args[1] == '' or args[2] == '' or args[3] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if values[4] == 'completed' then",
    "    return cjson.encode({status='unchanged', currentStatus='completed'})",
    '  end',
    "  if values[4] == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus='disconnected'})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', 'completed')",
    "  redis.call('DEL', keys[2])",
    "  redis.call('ZREM', keys[3], values[1])",
    '  local event = {',
    "    id=args[3], version=1, type='session.completed', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    "    payload={previousStatus=values[4], currentStatus='completed'}",
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='completed', event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_disconnect(keys, args)',
    '  if #keys ~= 5 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local expected_deadline = tonumber(args[4])',
    "  if args[1] == '' or args[2] == '' or args[3] == '' or not expected_deadline then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  local current_deadline = redis.call('ZSCORE', keys[3], values[1])",
    '  if not current_deadline or tonumber(current_deadline) ~= expected_deadline then',
    "    return cjson.encode({status='unchanged'})",
    '  end',
    "  if values[4] == 'completed' or values[4] == 'disconnected' then",
    "    redis.call('ZREM', keys[3], values[1])",
    "    return cjson.encode({status='unchanged'})",
    '  end',
    "  local presence_ttl = redis.call('PTTL', keys[2])",
    '  if presence_ttl > 0 then',
    '    local clock = redis_now()',
    '    local reconciled_deadline = clock.milliseconds + presence_ttl',
    "    redis.call('ZADD', keys[3], reconciled_deadline, values[1])",
    "    return cjson.encode({status='reconciled', deadlineMs=reconciled_deadline})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', 'disconnected')",
    "  redis.call('DEL', keys[2])",
    "  redis.call('ZREM', keys[3], values[1])",
    '  local event = {',
    "    id=args[3], version=1, type='session.disconnected', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    "    payload={previousStatus=values[4], currentStatus='disconnected'}",
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='disconnected', event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function message_request(keys, args)',
    '  if #keys ~= 15 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local decoded, message = pcall(cjson.decode, args[1])',
    "  if not decoded or type(message) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local required = {'id', 'correlationId', 'projectId', 'sourceSessionId', 'sourceAgentId', 'targetSessionId', 'targetAgentId', 'selectionReason', 'kind', 'content', 'requestFingerprint'}",
    '  for _, field in ipairs(required) do',
    "    if type(message[field]) ~= 'string' or message[field] == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    "  if type(message.evidenceRequirements) ~= 'table' or type(message.timeoutMs) ~= 'number' or message.timeoutMs < 1 or message.timeoutMs ~= math.floor(message.timeoutMs) or args[2] == '' or args[3] == '' or (args[4] ~= '0' and args[4] ~= '1') then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local evidence_requirements_json = next(message.evidenceRequirements) == nil and '[]' or cjson.encode(message.evidenceRequirements)",
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'string') or not type_is(keys[4], 'zset') or not type_is(keys[5], 'zset') or not type_is(keys[6], 'zset') or not type_is(keys[7], 'zset') or not type_is(keys[8], 'zset') or not type_is(keys[9], 'hash') or not type_is(keys[10], 'string') or not type_is(keys[11], 'hash') or not type_is(keys[12], 'string') or not type_is(keys[13], 'stream') or not type_is(keys[14], 'stream') or not type_is(keys[15], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if args[4] == '1' then",
    "    if type(message.idempotencyKeyHash) ~= 'string' or message.idempotencyKeyHash == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    "    local existing_json = redis.call('GET', keys[3])",
    '    if existing_json then',
    '      local valid_existing, existing = pcall(cjson.decode, existing_json)',
    "      if not valid_existing or type(existing) ~= 'table' or type(existing.messageId) ~= 'string' or type(existing.correlationId) ~= 'string' or type(existing.fingerprint) ~= 'string' then",
    "        return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '      end',
    '      if existing.fingerprint ~= message.requestFingerprint then',
    "        return cjson.encode({status='error', code='IDEMPOTENCY_KEY_CONFLICT'})",
    '      end',
    "      return cjson.encode({status='existing', messageId=existing.messageId, correlationId=existing.correlationId})",
    '    end',
    '  end',
    "  if key_type(keys[1]) ~= 'none' or key_type(keys[2]) ~= 'none' then",
    "    return cjson.encode({status='error', code='MESSAGE_ID_CONFLICT'})",
    '  end',
    "  if key_type(keys[9]) == 'none' or key_type(keys[10]) == 'none' then",
    "    return cjson.encode({status='error', code='SOURCE_SESSION_INVALID'})",
    '  end',
    "  if key_type(keys[11]) == 'none' or key_type(keys[12]) == 'none' then",
    "    return cjson.encode({status='error', code='TARGET_SESSION_UNAVAILABLE'})",
    '  end',
    "  local source = redis.call('HMGET', keys[9], 'id', 'agentId', 'projectId', 'status')",
    "  local target = redis.call('HMGET', keys[11], 'id', 'agentId', 'projectId', 'status')",
    "  if source[1] ~= message.sourceSessionId or source[2] ~= message.sourceAgentId or not source[3] or not source[4] or source[4] == 'completed' or source[4] == 'disconnected' then",
    "    return cjson.encode({status='error', code='SOURCE_SESSION_INVALID'})",
    '  end',
    "  if target[1] ~= message.targetSessionId or target[2] ~= message.targetAgentId or not target[3] or not target[4] or target[4] == 'completed' or target[4] == 'disconnected' then",
    "    return cjson.encode({status='error', code='TARGET_SESSION_UNAVAILABLE'})",
    '  end',
    '  if source[3] ~= message.projectId or target[3] ~= message.projectId then',
    "    return cjson.encode({status='error', code='TARGET_PROJECT_MISMATCH'})",
    '  end',
    '  if not stream_appendable(keys[13]) or not stream_appendable(keys[14]) or not stream_appendable(keys[15]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    '  local deadline_ms = clock.milliseconds + message.timeoutMs',
    '  local deadline_at = iso_from_milliseconds(deadline_ms)',
    '  local stored = {',
    '    id=message.id, correlationId=message.correlationId, projectId=message.projectId,',
    '    sourceSessionId=message.sourceSessionId, sourceAgentId=message.sourceAgentId,',
    '    targetSessionId=message.targetSessionId, targetAgentId=message.targetAgentId,',
    '    selectionReason=message.selectionReason, kind=message.kind, content=message.content,',
    "    evidenceRequirements=message.evidenceRequirements, state='queued',",
    '    createdAt=clock.timestamp, updatedAt=clock.timestamp, deadlineAt=deadline_at',
    '  }',
    "  if type(message.subject) == 'string' then stored.subject = message.subject end",
    '  local inbox_item = {',
    "    messageId=message.id, correlationId=message.correlationId, itemKind='request',",
    '    sourceSessionId=message.sourceSessionId, targetSessionId=message.targetSessionId,',
    '    createdAt=clock.timestamp, payload={kind=message.kind, content=message.content,',
    '    evidenceRequirements=message.evidenceRequirements, deadlineAt=deadline_at}',
    '  }',
    '  if stored.subject then inbox_item.payload.subject = stored.subject end',
    "  local inbox_stream_id = redis.call('XADD', keys[13], '*', 'item', cjson.encode(inbox_item))",
    '  local event = {',
    "    id=args[3], version=1, type='message.requested', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=message.projectId, agentId=message.sourceAgentId,',
    '    sessionId=message.sourceSessionId, correlationId=message.correlationId,',
    "    payload={messageId=message.id, kind=message.kind, state='queued', sourceSessionId=message.sourceSessionId, targetSessionId=message.targetSessionId, selectionReason=message.selectionReason}",
    '  }',
    '  local event_json = cjson.encode(event)',
    "  redis.call('HSET', keys[1], 'id', stored.id, 'correlationId', stored.correlationId, 'projectId', stored.projectId, 'sourceSessionId', stored.sourceSessionId, 'sourceAgentId', stored.sourceAgentId, 'targetSessionId', stored.targetSessionId, 'targetAgentId', stored.targetAgentId, 'selectionReason', stored.selectionReason, 'kind', stored.kind, 'content', stored.content, 'evidenceRequirements', evidence_requirements_json, 'state', stored.state, 'createdAt', stored.createdAt, 'updatedAt', stored.updatedAt, 'deadlineAt', stored.deadlineAt, 'deadlineMs', deadline_ms, 'requestFingerprint', message.requestFingerprint, 'targetInboxStreamId', inbox_stream_id)",
    "  if stored.subject then redis.call('HSET', keys[1], 'subject', stored.subject) end",
    "  if args[4] == '1' then redis.call('HSET', keys[1], 'idempotencyKeyHash', message.idempotencyKeyHash) end",
    "  redis.call('SET', keys[2], message.id)",
    "  if args[4] == '1' then redis.call('SET', keys[3], cjson.encode({messageId=message.id, correlationId=message.correlationId, fingerprint=message.requestFingerprint})) end",
    "  redis.call('ZADD', keys[4], clock.milliseconds, message.id)",
    "  redis.call('ZADD', keys[5], clock.milliseconds, message.id)",
    "  redis.call('ZADD', keys[6], clock.milliseconds, message.id)",
    "  redis.call('ZADD', keys[7], clock.milliseconds, message.id)",
    "  redis.call('ZADD', keys[8], deadline_ms, message.id)",
    '  local streams = append_event(keys[14], keys[15], event_json)',
    "  return cjson.encode({status='created', message=stored, event=event, inboxStreamId=inbox_stream_id, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function message_projection(key)',
    "  local fields = redis.call('HGETALL', key)",
    '  if #fields == 0 then return nil end',
    '  local raw = {}',
    '  for index = 1, #fields, 2 do raw[fields[index]] = fields[index + 1] end',
    "  local evidence_ok, evidence = pcall(cjson.decode, raw.evidenceRequirements or '')",
    "  if not evidence_ok or type(evidence) ~= 'table' then return nil end",
    '  local result = {',
    '    id=raw.id, correlationId=raw.correlationId, projectId=raw.projectId,',
    '    sourceSessionId=raw.sourceSessionId, sourceAgentId=raw.sourceAgentId,',
    '    targetSessionId=raw.targetSessionId, targetAgentId=raw.targetAgentId,',
    '    selectionReason=raw.selectionReason, kind=raw.kind, content=raw.content,',
    '    evidenceRequirements=evidence, state=raw.state, createdAt=raw.createdAt,',
    '    updatedAt=raw.updatedAt, deadlineAt=raw.deadlineAt',
    '  }',
    '  if raw.subject then result.subject = raw.subject end',
    '  if raw.acknowledgedAt then result.acknowledgedAt = raw.acknowledgedAt end',
    '  if raw.processingAt then result.processingAt = raw.processingAt end',
    '  if raw.respondedAt then result.respondedAt = raw.respondedAt end',
    '  if raw.response then',
    '    local response_ok, response = pcall(cjson.decode, raw.response)',
    "    if not response_ok or type(response) ~= 'table' then return nil end",
    '    result.response = response',
    '  end',
    '  return result',
    'end',
    'local function message_transition(keys, args, target_state)',
    '  if #keys ~= 10 or #args ~= 9 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'stream') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') or not type_is(keys[6], 'stream') or not type_is(keys[7], 'zset') or not type_is(keys[8], 'zset') or not type_is(keys[9], 'string') or not type_is(keys[10], 'string') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='error', code='MESSAGE_NOT_FOUND'})",
    '  end',
    "  if args[1] == '' or args[3] == '' or args[4] == '' or args[7] == '' or args[8] == '' or (args[9] ~= '0' and args[9] ~= '1') then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'correlationId', 'projectId', 'sourceSessionId', 'sourceAgentId', 'targetSessionId', 'targetAgentId', 'state', 'targetInboxStreamId')",
    '  for index = 1, 9 do',
    "    if not values[index] or values[index] == '' then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  end',
    '  if values[2] ~= args[1] then',
    "    return cjson.encode({status='error', code='MESSAGE_NOT_FOUND'})",
    '  end',
    '  local current = values[8]',
    '  local projection = message_projection(keys[1])',
    "  if not projection then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  local terminal = {responded=true, rejected=true, timed_out=true, failed=true}',
    "  if target_state ~= 'timed_out' then",
    "    if args[2] == '' or args[2] ~= values[6] or key_type(keys[2]) == 'none' then",
    "      return cjson.encode({status='error', code='RESPONDER_SESSION_MISMATCH'})",
    '    end',
    "    local responder = redis.call('HMGET', keys[2], 'id', 'status')",
    '    if responder[1] ~= values[6] or not responder[2] then',
    "      return cjson.encode({status='error', code='RESPONDER_SESSION_MISMATCH'})",
    '    end',
    "    if current ~= target_state and (responder[2] == 'completed' or responder[2] == 'disconnected') then",
    "      return cjson.encode({status='error', code='RESPONDER_SESSION_MISMATCH'})",
    '    end',
    '  end',
    '  if current == target_state then',
    "    return cjson.encode({status='unchanged', message=projection})",
    '  end',
    '  if terminal[current] then',
    "    if target_state == 'timed_out' then return cjson.encode({status='unchanged', message=projection}) end",
    "    return cjson.encode({status='error', code='MESSAGE_TERMINAL'})",
    '  end',
    '  local allowed = {',
    '    queued={delivered=true, timed_out=true, failed=true},',
    '    delivered={acknowledged=true, processing=true, responded=true, rejected=true, timed_out=true, failed=true},',
    '    acknowledged={processing=true, responded=true, rejected=true, timed_out=true, failed=true},',
    '    processing={responded=true, rejected=true, timed_out=true, failed=true}',
    '  }',
    '  if not allowed[current] or not allowed[current][target_state] then',
    "    return cjson.encode({status='error', code='MESSAGE_TRANSITION_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  if target_state == 'timed_out' then",
    '    local expected_deadline = tonumber(args[6])',
    "    local stored_deadline = redis.call('ZSCORE', keys[7], values[1])",
    '    if not expected_deadline or not stored_deadline or tonumber(stored_deadline) ~= expected_deadline or clock.milliseconds < expected_deadline then',
    "      return cjson.encode({status='unchanged', message=projection})",
    '    end',
    '  end',
    '  local response = nil',
    "  if target_state == 'responded' or target_state == 'rejected' or target_state == 'failed' then",
    '    local response_ok',
    '    response_ok, response = pcall(cjson.decode, args[5])',
    "    if not response_ok or type(response) ~= 'table' or type(response.status) ~= 'string' or type(response.answer) ~= 'string' or response.answer == '' or type(response.evidence) ~= 'table' or type(response.verifiedAt) ~= 'string' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    "    if target_state == 'responded' and response.status ~= 'answered' and response.status ~= 'partially_answered' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    "    if target_state == 'rejected' and response.status ~= 'rejected' then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    "    if target_state == 'failed' and response.status ~= 'failed' then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    '  elseif args[5] ~= "" then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local terminal_target = terminal[target_state] == true',
    '  if not stream_appendable(keys[3]) or not stream_appendable(keys[4]) or (terminal_target and not stream_appendable(keys[6])) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'state', target_state, 'updatedAt', clock.timestamp)",
    "  if target_state == 'acknowledged' then redis.call('HSET', keys[1], 'acknowledgedAt', clock.timestamp) end",
    "  if target_state == 'processing' then redis.call('HSET', keys[1], 'processingAt', clock.timestamp) end",
    "  if target_state == 'responded' then redis.call('HSET', keys[1], 'respondedAt', clock.timestamp) end",
    "  if response then redis.call('HSET', keys[1], 'response', args[5]) end",
    '  if terminal_target then',
    "    redis.call('ZREM', keys[7], values[1])",
    "    redis.call('ZADD', keys[8], clock.milliseconds, values[1])",
    '    local notification = {',
    "      messageId=values[1], correlationId=values[2], itemKind='response',",
    '      sourceSessionId=values[6], targetSessionId=values[4], createdAt=clock.timestamp,',
    '      payload={state=target_state}',
    '    }',
    '    if response then notification.payload.response = response end',
    "    redis.call('XADD', keys[6], '*', 'item', cjson.encode(notification))",
    "    redis.call('XACK', keys[5], args[8], values[9])",
    "    if args[9] == '1' then redis.call('PEXPIRE', keys[9], tonumber(args[7])) end",
    '  end',
    '  local event_types = {',
    "    delivered='message.delivered', acknowledged='message.acknowledged',",
    "    processing='message.processing', responded='message.responded',",
    "    rejected='message.rejected', failed='message.failed', timed_out='message.timed_out'",
    '  }',
    '  local event = {',
    '    id=args[4], version=1, type=event_types[target_state], occurredAt=clock.timestamp,',
    '    workspaceId=args[3], projectId=values[3], agentId=values[7], sessionId=values[6],',
    '    correlationId=values[2], payload={messageId=values[1], previousState=current, currentState=target_state}',
    '  }',
    '  local streams = append_event(keys[3], keys[4], cjson.encode(event))',
    '  local updated = message_projection(keys[1])',
    "  if not updated then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    "  return cjson.encode({status='updated', message=updated, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    "local function message_delivered(keys, args) return message_transition(keys, args, 'delivered') end",
    "local function message_acknowledge(keys, args) return message_transition(keys, args, 'acknowledged') end",
    "local function message_processing(keys, args) return message_transition(keys, args, 'processing') end",
    "local function message_respond(keys, args) return message_transition(keys, args, 'responded') end",
    "local function message_reject(keys, args) return message_transition(keys, args, 'rejected') end",
    "local function message_fail(keys, args) return message_transition(keys, args, 'failed') end",
    "local function message_timeout(keys, args) return message_transition(keys, args, 'timed_out') end",
    'local function control_append_event(global_stream, project_stream, event_json)',
    "  local global_stream_id = redis.call('XADD', global_stream, '*', 'event', event_json)",
    '  local project_stream_id = global_stream_id',
    '  if project_stream ~= global_stream then',
    "    project_stream_id = redis.call('XADD', project_stream, '*', 'event', event_json)",
    '  end',
    '  return {globalStreamId=global_stream_id, projectStreamId=project_stream_id}',
    'end',
    // Work leases.
    //
    // Path normalization, case folding and the trailing-separator convention
    // live in `@luwi/protocol`; what happens here is only the part that has to
    // be atomic — compare already-normalized match forms against the project's
    // held leases and either write the record with its event, or refuse with
    // the holder. Every key it touches is declared, so nothing is derived from
    // another key's name.
    //
    // The project's held leases are one hash keyed by lease id, whose values
    // carry just enough to answer a conflict: match form, holder, and expiry.
    // That is what keeps the scan to a single declared key.
    'local function lease_overlaps(left, right)',
    '  return string.sub(left, 1, string.len(right)) == right or string.sub(right, 1, string.len(left)) == left',
    'end',
    'local function lease_acquire(keys, args)',
    '  if #keys ~= 6 or #args ~= 6 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'zset') or not type_is(keys[5], 'stream') or not type_is(keys[6], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local lease_ok, lease = pcall(cjson.decode, args[1])',
    '  local granted_ok, granted_event = pcall(cjson.decode, args[2])',
    '  local denied_ok, denied_event = pcall(cjson.decode, args[3])',
    "  if not lease_ok or type(lease) ~= 'table' or not granted_ok or type(granted_event) ~= 'table' or not denied_ok or type(denied_event) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if type(lease.id) ~= 'string' or lease.id == '' or type(lease.matchPath) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local now_ms = tonumber(args[4])',
    '  local expires_ms = tonumber(args[5])',
    '  local max_active = tonumber(args[6])',
    '  if not now_ms or not expires_ms or not max_active then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then return cjson.encode({status='conflict'}) end",
    '  if not stream_appendable(keys[5]) or not stream_appendable(keys[6]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  local held = redis.call('HGETALL', keys[2])",
    '  local active = 0',
    '  for index = 2, #held, 2 do',
    '    local other_ok, other = pcall(cjson.decode, held[index])',
    "    if other_ok and type(other) == 'table' and type(other.matchPath) == 'string' then",
    // An entry past its expiry is ignored rather than deleted: removing it is
    // the sweep's job, and the sweep owns the `lease.expired` event with it.
    '      local other_expiry = tonumber(other.expiresMs)',
    '      if other_expiry and other_expiry > now_ms then',
    '        active = active + 1',
    '        if lease_overlaps(lease.matchPath, other.matchPath) then',
    '          local streams = control_append_event(keys[5], keys[6], args[3])',
    // The conflict is built field by field rather than returned as the stored
    // detail record: the detail carries the match form and a numeric expiry
    // that the wire contract does not have, and that contract is strict.
    '          local conflict = {leaseId=other.leaseId, sessionId=other.sessionId, agentId=other.agentId, path=other.path, reason=other.reason, expiresAt=other.expiresAt}',
    "          return cjson.encode({status='denied', conflict=conflict, event=denied_event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    '        end',
    '      end',
    '    end',
    '  end',
    '  if active >= max_active then',
    "    return cjson.encode({status='error', code='LEASE_LIMIT_REACHED'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', lease.id, 'json', args[1])",
    "  redis.call('HSET', keys[2], lease.id, cjson.encode({leaseId=lease.id, matchPath=lease.matchPath, path=lease.path, sessionId=lease.sessionId, agentId=lease.agentId, reason=lease.reason, expiresAt=lease.expiresAt, expiresMs=expires_ms}))",
    "  redis.call('SADD', keys[3], lease.id)",
    "  redis.call('ZADD', keys[4], expires_ms, lease.id)",
    '  local streams = control_append_event(keys[5], keys[6], args[2])',
    "  return cjson.encode({status='granted', lease=lease, event=granted_event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function lease_transition(keys, args, stays_held)',
    '  if #keys ~= 6 or #args ~= 5 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'zset') or not type_is(keys[5], 'stream') or not type_is(keys[6], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then return cjson.encode({status='not_found'}) end",
    "  local current_json = redis.call('HGET', keys[1], 'json')",
    '  local current_ok, current = pcall(cjson.decode, current_json or "")',
    "  if not current_ok or type(current) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if current.state ~= 'held' then return cjson.encode({status='state_conflict', lease=current}) end",
    // Only the holder renews or releases. A lease another session can drop is
    // not a lease. The sweep passes an empty holder because expiry is the
    // runtime's own transition, not a caller's.
    "  if args[1] ~= '' and current.sessionId ~= args[1] then",
    "    return cjson.encode({status='not_holder', lease=current})",
    '  end',
    '  local updated_ok, updated = pcall(cjson.decode, args[2])',
    '  local event_ok, event = pcall(cjson.decode, args[3])',
    "  if not updated_ok or type(updated) ~= 'table' or not event_ok or type(event) ~= 'table' or updated.id ~= current.id then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[5]) or not stream_appendable(keys[6]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local expires_ms = tonumber(args[4])',
    "  redis.call('HSET', keys[1], 'id', updated.id, 'json', args[2])",
    "  if stays_held == 'held' and expires_ms then",
    "    redis.call('HSET', keys[2], updated.id, cjson.encode({leaseId=updated.id, matchPath=updated.matchPath, path=updated.path, sessionId=updated.sessionId, agentId=updated.agentId, reason=updated.reason, expiresAt=updated.expiresAt, expiresMs=expires_ms}))",
    "    redis.call('ZADD', keys[4], expires_ms, updated.id)",
    '  else',
    "    redis.call('HDEL', keys[2], updated.id)",
    "    redis.call('SREM', keys[3], updated.id)",
    "    redis.call('ZREM', keys[4], updated.id)",
    '  end',
    '  local streams = control_append_event(keys[5], keys[6], args[3])',
    "  return cjson.encode({status='updated', lease=updated, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    "local function lease_renew(keys, args) return lease_transition(keys, args, 'held') end",
    "local function lease_release(keys, args) return lease_transition(keys, args, 'closed') end",
    "local function lease_expire(keys, args) return lease_transition(keys, args, 'closed') end",
    'local function control_upsert(keys, args)',
    '  if #keys < 4 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'set') or not type_is(keys[3], 'stream') or not type_is(keys[4], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  for index = 5, #keys do',
    "    if not type_is(keys[index], 'set') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  end',
    "  if args[1] ~= 'create' and args[1] ~= 'update' and args[1] ~= 'upsert' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local entity_ok, entity = pcall(cjson.decode, args[2])',
    '  local event_ok, event = pcall(cjson.decode, args[3])',
    "  if not entity_ok or type(entity) ~= 'table' or not event_ok or type(event) ~= 'table' or type(entity.id) ~= 'string' or entity.id ~= args[4] or type(event.id) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local exists = key_type(keys[1]) ~= 'none'",
    "  if args[1] == 'create' and exists then return cjson.encode({status='conflict'}) end",
    "  if args[1] == 'update' and not exists then return cjson.encode({status='not_found'}) end",
    '  if not stream_appendable(keys[3]) or not stream_appendable(keys[4]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', entity.id, 'json', args[2])",
    "  redis.call('SADD', keys[2], entity.id)",
    "  for index = 5, #keys do redis.call('SADD', keys[index], entity.id) end",
    '  local streams = control_append_event(keys[3], keys[4], args[3])',
    "  return cjson.encode({status=exists and 'updated' or 'created', entity=entity, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function control_delete(keys, args)',
    '  if #keys < 4 or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'set') or not type_is(keys[3], 'stream') or not type_is(keys[4], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then return cjson.encode({status='not_found'}) end",
    '  local entity_ok, entity = pcall(cjson.decode, args[1])',
    '  local event_ok, event = pcall(cjson.decode, args[2])',
    "  if not entity_ok or type(entity) ~= 'table' or not event_ok or type(event) ~= 'table' or type(entity.id) ~= 'string' or entity.id ~= args[3] then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[3]) or not stream_appendable(keys[4]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('DEL', keys[1])",
    "  redis.call('SREM', keys[2], entity.id)",
    "  for index = 5, #keys do redis.call('SREM', keys[index], entity.id) end",
    '  local streams = control_append_event(keys[3], keys[4], args[2])',
    "  return cjson.encode({status='deleted', entity=entity, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function control_plan_transition(keys, args)',
    '  if #keys ~= 4 or #args ~= 6 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'stream') or not type_is(keys[3], 'stream') or not type_is(keys[4], 'zset') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local plan_ok, plan = pcall(cjson.decode, args[2])',
    '  local event_ok, event = pcall(cjson.decode, args[3])',
    "  if not plan_ok or type(plan) ~= 'table' or not event_ok or type(event) ~= 'table' or type(plan.id) ~= 'string' or plan.id ~= args[4] or type(plan.state) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local exists = key_type(keys[1]) ~= 'none'",
    "  if args[1] == '__missing__' then",
    "    if exists then return cjson.encode({status='conflict'}) end",
    '  else',
    "    if not exists then return cjson.encode({status='not_found'}) end",
    "    local previous_json = redis.call('HGET', keys[1], 'json')",
    '    local previous_ok, previous = pcall(cjson.decode, previous_json or "")',
    "    if not previous_ok or type(previous) ~= 'table' or previous.state ~= args[1] then",
    "      return cjson.encode({status='state_conflict'})",
    '    end',
    '  end',
    '  if not stream_appendable(keys[2]) or not stream_appendable(keys[3]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', plan.id, 'json', args[2])",
    '  local expiry = tonumber(args[5])',
    "  if args[6] == 'track' and expiry and expiry > 0 then",
    "    redis.call('ZADD', keys[4], expiry, plan.id)",
    '  else',
    "    redis.call('ZREM', keys[4], plan.id)",
    '  end',
    '  local streams = control_append_event(keys[2], keys[3], args[3])',
    "  return cjson.encode({status=exists and 'updated' or 'created', plan=plan, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function control_plan_complete(keys, args)',
    '  if #keys ~= 6 or #args ~= 6 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') or not type_is(keys[6], 'zset') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then return cjson.encode({status='not_found'}) end",
    "  if key_type(keys[2]) ~= 'none' then return cjson.encode({status='conflict'}) end",
    "  local previous_json = redis.call('HGET', keys[1], 'json')",
    '  local previous_ok, previous = pcall(cjson.decode, previous_json or "")',
    "  if not previous_ok or type(previous) ~= 'table' or previous.state ~= args[1] then",
    "    return cjson.encode({status='state_conflict'})",
    '  end',
    '  local plan_ok, plan = pcall(cjson.decode, args[2])',
    '  local operation_ok, operation = pcall(cjson.decode, args[3])',
    '  local event_ok, event = pcall(cjson.decode, args[4])',
    "  if not plan_ok or type(plan) ~= 'table' or not operation_ok or type(operation) ~= 'table' or not event_ok or type(event) ~= 'table' or type(plan.id) ~= 'string' or plan.id ~= args[5] or type(operation.id) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', plan.id, 'json', args[2])",
    "  redis.call('HSET', keys[2], 'id', operation.id, 'json', args[3])",
    "  redis.call('SADD', keys[3], operation.id)",
    '  local expiry = tonumber(args[6])',
    "  if expiry and expiry > 0 then redis.call('ZADD', keys[6], expiry, plan.id) end",
    '  local streams = control_append_event(keys[4], keys[5], args[4])',
    "  return cjson.encode({status='updated', plan=plan, operation=operation, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function usage_ingest(keys, args)',
    '  if #keys ~= 16 or #args ~= 6 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  for index = 2, 5 do',
    "    if not type_is(keys[index], 'set') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  end',
    "  if not type_is(keys[6], 'string') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  for index = 7, 14 do',
    "    if not type_is(keys[index], 'hash') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  end',
    "  if not type_is(keys[15], 'stream') or not type_is(keys[16], 'stream') then return cjson.encode({status='error', code='REDIS_STATE_INVALID'}) end",
    '  local record_ok, record = pcall(cjson.decode, args[1])',
    '  local event_ok, event = pcall(cjson.decode, args[2])',
    '  local deltas_ok, deltas = pcall(cjson.decode, args[6])',
    "  if not record_ok or type(record) ~= 'table' or not event_ok or type(event) ~= 'table' or not deltas_ok or type(deltas) ~= 'table' or type(record.id) ~= 'string' or record.id ~= args[3] or type(event.id) ~= 'string' or type(args[5]) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  for field, delta in pairs(deltas) do',
    "    if type(field) ~= 'string' or type(delta) ~= 'number' or delta < 0 or delta % 1 ~= 0 then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then return cjson.encode({status='duplicate', existingUsageId=record.id}) end",
    "  if args[4] ~= '' and key_type(keys[6]) ~= 'none' then",
    "    return cjson.encode({status='duplicate', existingUsageId=redis.call('GET', keys[6])})",
    '  end',
    '  if not stream_appendable(keys[15]) or not stream_appendable(keys[16]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'id', record.id, 'json', args[1])",
    "  for index = 2, 5 do redis.call('SADD', keys[index], record.id) end",
    "  if args[4] ~= '' then redis.call('SET', keys[6], record.id) end",
    '  for index = 7, 14 do',
    "    redis.call('HINCRBY', keys[index], 'recordCount', 1)",
    "    local earliest = redis.call('HGET', keys[index], 'observedFrom')",
    "    local latest = redis.call('HGET', keys[index], 'observedTo')",
    "    if not earliest or args[5] < earliest then redis.call('HSET', keys[index], 'observedFrom', args[5]) end",
    "    if not latest or args[5] > latest then redis.call('HSET', keys[index], 'observedTo', args[5]) end",
    '    for field, delta in pairs(deltas) do',
    "      redis.call('HINCRBY', keys[index], field, delta)",
    '    end',
    '  end',
    '  local streams = control_append_event(keys[15], keys[16], args[2])',
    "  return cjson.encode({status='created', usage=record, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function intelligence_batch_transition(keys, args)',
    '  if #keys < 2 or #args ~= 2 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'stream') or not type_is(keys[2], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local operations_ok, operations = pcall(cjson.decode, args[1])',
    '  local event_ok, event = pcall(cjson.decode, args[2])',
    "  if not operations_ok or type(operations) ~= 'table' or #operations > 100000 or not event_ok or type(event) ~= 'table' or type(event.id) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  for _, operation in ipairs(operations) do',
    "    if type(operation) ~= 'table' or type(operation.key) ~= 'number' or operation.key % 1 ~= 0 or operation.key < 3 or operation.key > #keys or type(operation.kind) ~= 'string' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '    local key = keys[operation.key]',
    "    if operation.kind == 'hash_json' then",
    "      if type(operation.id) ~= 'string' or operation.id == '' or type(operation.json) ~= 'string' or not type_is(key, 'hash') then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    "    elseif operation.kind == 'set_add' or operation.kind == 'set_remove' then",
    "      if type(operation.member) ~= 'string' or operation.member == '' or not type_is(key, 'set') then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    "    elseif operation.kind ~= 'delete' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    '  if not stream_appendable(keys[1]) or not stream_appendable(keys[2]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  for _, operation in ipairs(operations) do',
    '    local key = keys[operation.key]',
    "    if operation.kind == 'hash_json' then",
    "      redis.call('HSET', key, 'id', operation.id, 'json', operation.json)",
    "    elseif operation.kind == 'set_add' then",
    "      redis.call('SADD', key, operation.member)",
    "    elseif operation.kind == 'set_remove' then",
    "      redis.call('SREM', key, operation.member)",
    '    else',
    "      redis.call('DEL', key)",
    '    end',
    '  end',
    '  local streams = control_append_event(keys[1], keys[2], args[2])',
    "  return cjson.encode({status='updated', event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function graph_projection_failure(keys, args)',
    '  if #keys ~= 2 or #args ~= 1 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'stream') or not type_is(keys[2], 'string') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local failure_ok, failure = pcall(cjson.decode, args[1])',
    "  if not failure_ok or type(failure) ~= 'table' or type(failure.id) ~= 'string' or failure.id == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[1]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  local stream_id = redis.call('XADD', keys[1], 'MAXLEN', '~', 1000, '*', 'failure', args[1])",
    "  redis.call('SET', keys[2], 'degraded')",
    "  return cjson.encode({status='updated', streamId=stream_id})",
    'end',
    'local function graph_rebuild_transition(keys, args)',
    '  if (#keys ~= 6 and #keys ~= 7) or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'string') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'string') or not type_is(keys[5], 'string') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if not type_is(keys[6], 'stream') or (#keys == 7 and not type_is(keys[7], 'stream')) then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local operation_ok, operation = pcall(cjson.decode, args[1])',
    '  local event_ok, event = pcall(cjson.decode, args[2])',
    "  if not operation_ok or type(operation) ~= 'table' or not event_ok or type(event) ~= 'table' or type(operation.id) ~= 'string' or operation.id ~= args[3] or type(event.id) ~= 'string' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if operation.state ~= 'completed' and operation.state ~= 'failed' then",
    "    return cjson.encode({status='error', code='GRAPH_REBUILD_FAILED'})",
    '  end',
    "  if redis.call('GET', keys[4]) ~= args[3] then",
    "    return cjson.encode({status='error', code='GRAPH_REBUILD_OWNERSHIP_LOST'})",
    '  end',
    '  if not stream_appendable(keys[6]) or (#keys == 7 and not stream_appendable(keys[7])) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if operation.state == 'completed' then",
    "    if type(operation.shadowGeneration) ~= 'string' then return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'}) end",
    "    redis.call('SET', keys[1], operation.shadowGeneration)",
    "    redis.call('SET', keys[5], 'healthy')",
    '  else',
    "    redis.call('SET', keys[5], 'degraded')",
    '  end',
    "  redis.call('HSET', keys[2], 'id', operation.id, 'json', args[1])",
    "  redis.call('SADD', keys[3], operation.id)",
    "  redis.call('DEL', keys[4])",
    "  local global_stream_id = redis.call('XADD', keys[6], '*', 'event', args[2])",
    '  local project_stream_id = nil',
    "  if #keys == 7 then project_stream_id = redis.call('XADD', keys[7], '*', 'event', args[2]) end",
    "  return cjson.encode({status='updated', operation=operation, event=event, globalStreamId=global_stream_id, projectStreamId=project_stream_id})",
    'end',
    'local function not_implemented(keys, args)',
    "  return cjson.encode({status='not_implemented'})",
    'end',
    'local function library_version(keys, args)',
    `  return cjson.encode({version=${registry.version}, libraryName='${registry.libraryName}'})`,
    'end',
    register(registry.functions.projectRegister, 'project_register'),
    register(registry.functions.sessionRegister, 'session_register'),
    register(registry.functions.sessionHeartbeat, 'session_heartbeat'),
    register(registry.functions.sessionStatus, 'session_status'),
    register(registry.functions.sessionClose, 'session_close'),
    register(registry.functions.sessionDisconnect, 'session_disconnect'),
    register(registry.functions.messageRequest, 'message_request'),
    register(registry.functions.messageDelivered, 'message_delivered'),
    register(registry.functions.messageAcknowledge, 'message_acknowledge'),
    register(registry.functions.messageProcessing, 'message_processing'),
    register(registry.functions.messageRespond, 'message_respond'),
    register(registry.functions.messageReject, 'message_reject'),
    register(registry.functions.messageFail, 'message_fail'),
    register(registry.functions.messageTimeout, 'message_timeout'),
    register(registry.functions.leaseAcquire, 'lease_acquire'),
    register(registry.functions.leaseRenew, 'lease_renew'),
    register(registry.functions.leaseRelease, 'lease_release'),
    register(registry.functions.leaseExpire, 'lease_expire'),
    register(registry.functions.controlUpsert, 'control_upsert'),
    register(registry.functions.controlDelete, 'control_delete'),
    register(registry.functions.controlPlanTransition, 'control_plan_transition'),
    register(registry.functions.controlPlanComplete, 'control_plan_complete'),
    register(registry.functions.usageIngest, 'usage_ingest'),
    register(registry.functions.graphRebuildTransition, 'graph_rebuild_transition'),
    register(registry.functions.intelligenceBatchTransition, 'intelligence_batch_transition'),
    register(registry.functions.graphProjectionFailure, 'graph_projection_failure'),
    register(registry.functions.version, 'library_version'),
    '',
  ].join('\n');

  return {
    registry,
    source,
    contentHash: createHash('sha256').update(source).digest('hex'),
  };
}
