import { createHash } from 'node:crypto';

import type { RedisFunctionRegistry } from './function-registry.js';

export type RedisFunctionLibrary = {
  registry: RedisFunctionRegistry;
  source: string;
  contentHash: string;
};

function register(functionName: string, callback: string): string {
  return `redis.register_function{function_name='${functionName}', callback=${callback}}`;
}

export function buildFunctionLibrary(registry: RedisFunctionRegistry): RedisFunctionLibrary {
  const source = [
    `#!lua name=${registry.libraryName}`,
    'local function key_type(key)',
    "  local result = redis.call('TYPE', key)",
    "  if type(result) == 'table' then return result['ok'] end",
    '  return result',
    'end',
    'local function type_is(key, expected)',
    '  local actual = key_type(key)',
    "  return actual == 'none' or actual == expected",
    'end',
    'local function stream_appendable(key)',
    "  if key_type(key) == 'none' then return true end",
    "  local info = redis.call('XINFO', 'STREAM', key)",
    '  for index = 1, #info, 2 do',
    "    if info[index] == 'last-generated-id' then",
    "      return info[index + 1] ~= '18446744073709551615-18446744073709551615'",
    '    end',
    '  end',
    '  return false',
    'end',
    'local function redis_now()',
    "  local now = redis.call('TIME')",
    '  local seconds = tonumber(now[1])',
    '  local milliseconds = math.floor(tonumber(now[2]) / 1000)',
    '  local days = math.floor(seconds / 86400)',
    '  local seconds_of_day = seconds - (days * 86400)',
    '  local era = math.floor(days / 146097)',
    '  local day_of_era = days - (era * 146097) + 719468',
    '  era = math.floor(day_of_era / 146097)',
    '  day_of_era = day_of_era - (era * 146097)',
    '  local year_of_era = math.floor((day_of_era - math.floor(day_of_era / 1460) + math.floor(day_of_era / 36524) - math.floor(day_of_era / 146096)) / 365)',
    '  local year = year_of_era + (era * 400)',
    '  local day_of_year = day_of_era - ((365 * year_of_era) + math.floor(year_of_era / 4) - math.floor(year_of_era / 100))',
    '  local month_prime = math.floor(((5 * day_of_year) + 2) / 153)',
    '  local day = day_of_year - math.floor(((153 * month_prime) + 2) / 5) + 1',
    '  local month',
    '  if month_prime < 10 then month = month_prime + 3 else month = month_prime - 9 end',
    '  if month <= 2 then year = year + 1 end',
    '  local hour = math.floor(seconds_of_day / 3600)',
    '  local minute = math.floor((seconds_of_day % 3600) / 60)',
    '  local second = seconds_of_day % 60',
    "  return {timestamp=string.format('%04d-%02d-%02dT%02d:%02d:%02d.%03dZ', year, month, day, hour, minute, second, milliseconds), milliseconds=(seconds * 1000) + milliseconds}",
    'end',
    'local function append_event(global_stream, project_stream, event_json)',
    "  local global_stream_id = redis.call('XADD', global_stream, '*', 'event', event_json)",
    "  local project_stream_id = redis.call('XADD', project_stream, '*', 'event', event_json)",
    '  return {globalStreamId=global_stream_id, projectStreamId=project_stream_id}',
    'end',
    'local function project_register(keys, args)',
    '  if #keys ~= 5 or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local decoded, project = pcall(cjson.decode, args[1])',
    "  if not decoded or type(project) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local required = {'id', 'name', 'localPath', 'canonicalPath', 'identityPath', 'pathIdentityHash'}",
    '  for _, field in ipairs(required) do',
    "    if type(project[field]) ~= 'string' or project[field] == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    "  if type(args[2]) ~= 'string' or args[2] == '' or type(args[3]) ~= 'string' or args[3] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'set') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then",
    "    return cjson.encode({status='error', code='PROJECT_ID_CONFLICT'})",
    '  end',
    "  local existing_identity = redis.call('GET', keys[2])",
    '  if existing_identity then',
    '    local valid, existing = pcall(cjson.decode, existing_identity)',
    "    if not valid or type(existing) ~= 'table' or type(existing.projectId) ~= 'string' or type(existing.identityPath) ~= 'string' or type(existing.canonicalPath) ~= 'string' then",
    "      return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '    end',
    '    if existing.identityPath == project.identityPath then',
    "      return cjson.encode({status='conflict', reason='duplicate', existingProjectId=existing.projectId, canonicalPath=existing.canonicalPath})",
    '    end',
    "    return cjson.encode({status='conflict', reason='hash_collision'})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local timestamp = redis_now().timestamp',
    '  local stored = {',
    '    id=project.id, name=project.name, localPath=project.localPath,',
    '    canonicalPath=project.canonicalPath, createdAt=timestamp, updatedAt=timestamp',
    '  }',
    "  if type(project.repositoryUrl) == 'string' then stored.repositoryUrl = project.repositoryUrl end",
    "  if type(project.defaultBranch) == 'string' then stored.defaultBranch = project.defaultBranch end",
    '  local event = {',
    "    id=args[3], version=1, type='project.registered', occurredAt=timestamp,",
    '    workspaceId=args[2], projectId=project.id, payload={project=stored}',
    '  }',
    '  local event_json = cjson.encode(event)',
    "  redis.call('HSET', keys[1], 'id', stored.id, 'name', stored.name, 'localPath', stored.localPath, 'canonicalPath', stored.canonicalPath, 'identityPath', project.identityPath, 'pathIdentityHash', project.pathIdentityHash, 'createdAt', stored.createdAt, 'updatedAt', stored.updatedAt)",
    "  if stored.repositoryUrl then redis.call('HSET', keys[1], 'repositoryUrl', stored.repositoryUrl) end",
    "  if stored.defaultBranch then redis.call('HSET', keys[1], 'defaultBranch', stored.defaultBranch) end",
    "  redis.call('SET', keys[2], cjson.encode({projectId=project.id, identityPath=project.identityPath, canonicalPath=project.canonicalPath}))",
    "  redis.call('SADD', keys[3], project.id)",
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='created', project=stored, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_register(keys, args)',
    '  if #keys ~= 8 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local decoded, session = pcall(cjson.decode, args[1])',
    "  if not decoded or type(session) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local required = {'id', 'agentId', 'projectId', 'status', 'workingDirectory', 'metadataJson'}",
    '  for _, field in ipairs(required) do',
    "    if type(session[field]) ~= 'string' or session[field] == '' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '  end',
    "  if session.status ~= 'starting' or type(args[2]) ~= 'string' or args[2] == '' or type(args[3]) ~= 'string' or args[3] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local ttl = tonumber(args[4])',
    '  if not ttl or ttl < 1 or ttl ~= math.floor(ttl) then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    '  local metadata_valid, metadata = pcall(cjson.decode, session.metadataJson)',
    "  if not metadata_valid or type(metadata) ~= 'table' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'hash') or not type_is(keys[3], 'set') or not type_is(keys[4], 'set') or not type_is(keys[5], 'string') or not type_is(keys[6], 'zset') or not type_is(keys[7], 'stream') or not type_is(keys[8], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) ~= 'none' then",
    "    return cjson.encode({status='error', code='SESSION_ID_CONFLICT'})",
    '  end',
    "  if key_type(keys[2]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='project'})",
    '  end',
    "  local stored_project_id = redis.call('HGET', keys[2], 'id')",
    '  if stored_project_id ~= session.projectId then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  if not stream_appendable(keys[7]) or not stream_appendable(keys[8]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    '  local stored = {',
    "    id=session.id, agentId=session.agentId, projectId=session.projectId, status='starting',",
    '    workingDirectory=session.workingDirectory, startedAt=clock.timestamp,',
    '    lastHeartbeatAt=clock.timestamp, metadata=metadata',
    '  }',
    "  if type(session.taskSummary) == 'string' then stored.taskSummary = session.taskSummary end",
    "  if type(session.branch) == 'string' then stored.branch = session.branch end",
    "  if type(session.worktreePath) == 'string' then stored.worktreePath = session.worktreePath end",
    '  local event = {',
    "    id=args[3], version=1, type='session.registered', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=session.projectId, agentId=session.agentId,',
    '    sessionId=session.id, payload={session=stored}',
    '  }',
    '  local event_json = cjson.encode(event)',
    "  redis.call('HSET', keys[1], 'id', stored.id, 'agentId', stored.agentId, 'projectId', stored.projectId, 'status', stored.status, 'workingDirectory', stored.workingDirectory, 'startedAt', stored.startedAt, 'lastHeartbeatAt', stored.lastHeartbeatAt, 'metadata', session.metadataJson)",
    "  if stored.taskSummary then redis.call('HSET', keys[1], 'taskSummary', stored.taskSummary) end",
    "  if stored.branch then redis.call('HSET', keys[1], 'branch', stored.branch) end",
    "  if stored.worktreePath then redis.call('HSET', keys[1], 'worktreePath', stored.worktreePath) end",
    "  redis.call('SADD', keys[3], session.id)",
    "  redis.call('SADD', keys[4], session.id)",
    "  redis.call('SET', keys[5], session.id, 'PX', ttl)",
    "  redis.call('ZADD', keys[6], clock.milliseconds + ttl, session.id)",
    '  local streams = append_event(keys[7], keys[8], event_json)',
    "  return cjson.encode({status='created', session=stored, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_status(keys, args)',
    '  if #keys ~= 5 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local target = args[1]',
    '  local allowed = {idle=true, thinking=true, tool_running=true, waiting_for_input=true, waiting_for_agent=true, blocked=true, completed=true}',
    '  if not allowed[target] or args[2] == "" or args[3] == "" or args[4] == "" then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[2] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local current = values[4]',
    '  if current == target then',
    "    return cjson.encode({status='unchanged', currentStatus=current})",
    '  end',
    "  if current == 'completed' or current == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus=current})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', target)",
    "  if target == 'completed' then",
    "    redis.call('DEL', keys[2])",
    "    redis.call('ZREM', keys[3], values[1])",
    '  end',
    '  local event = {',
    "    id=args[4], version=1, type='session.status.changed', occurredAt=clock.timestamp,",
    '    workspaceId=args[3], projectId=values[3], agentId=values[2], sessionId=values[1],',
    '    payload={previousStatus=current, currentStatus=target}',
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='updated', previousStatus=current, currentStatus=target, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_heartbeat(keys, args)',
    '  if #keys ~= 5 or #args ~= 7 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local ttl = tonumber(args[4])',
    '  local interval = tonumber(args[5])',
    "  if args[1] == '' or args[2] == '' or args[3] == '' or not ttl or ttl < 1 or ttl ~= math.floor(ttl) or not interval or interval < 0 or interval ~= math.floor(interval) or (args[6] ~= '0' and args[6] ~= '1') then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status', 'metadata', 'lastHeartbeatEventAt')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or not values[5] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if values[4] == 'completed' or values[4] == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus=values[4]})",
    '  end',
    '  local metadata_changed = false',
    "  if args[6] == '1' then",
    '    local valid_metadata, decoded_metadata = pcall(cjson.decode, args[7])',
    "    if not valid_metadata or type(decoded_metadata) ~= 'table' then",
    "      return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '    end',
    '    metadata_changed = values[5] ~= args[7]',
    '  end',
    '  local clock = redis_now()',
    '  local last_event_ms = tonumber(values[6])',
    '  local emit_event = not last_event_ms or (clock.milliseconds - last_event_ms) >= interval or metadata_changed',
    '  if emit_event and (not stream_appendable(keys[4]) or not stream_appendable(keys[5])) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  redis.call('HSET', keys[1], 'lastHeartbeatAt', clock.timestamp)",
    "  if args[6] == '1' then redis.call('HSET', keys[1], 'metadata', args[7]) end",
    "  redis.call('SET', keys[2], values[1], 'PX', ttl)",
    "  redis.call('ZADD', keys[3], clock.milliseconds + ttl, values[1])",
    '  if not emit_event then',
    "    return cjson.encode({status='renewed', eventEmitted=false, lastHeartbeatAt=clock.timestamp})",
    '  end',
    "  redis.call('HSET', keys[1], 'lastHeartbeatEventAt', clock.milliseconds)",
    '  local event = {',
    "    id=args[3], version=1, type='session.heartbeat', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    '    payload={metadataChanged=metadata_changed}',
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='renewed', eventEmitted=true, lastHeartbeatAt=clock.timestamp, event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_close(keys, args)',
    '  if #keys ~= 5 or #args ~= 3 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    "  if args[1] == '' or args[2] == '' or args[3] == '' then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if values[4] == 'completed' then",
    "    return cjson.encode({status='unchanged', currentStatus='completed'})",
    '  end',
    "  if values[4] == 'disconnected' then",
    "    return cjson.encode({status='terminal', currentStatus='disconnected'})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', 'completed')",
    "  redis.call('DEL', keys[2])",
    "  redis.call('ZREM', keys[3], values[1])",
    '  local event = {',
    "    id=args[3], version=1, type='session.completed', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    "    payload={previousStatus=values[4], currentStatus='completed'}",
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='completed', event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function session_disconnect(keys, args)',
    '  if #keys ~= 5 or #args ~= 4 then',
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  if not type_is(keys[1], 'hash') or not type_is(keys[2], 'string') or not type_is(keys[3], 'zset') or not type_is(keys[4], 'stream') or not type_is(keys[5], 'stream') then",
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  if key_type(keys[1]) == 'none' then",
    "    return cjson.encode({status='not_found', entity='session'})",
    '  end',
    '  local expected_deadline = tonumber(args[4])',
    "  if args[1] == '' or args[2] == '' or args[3] == '' or not expected_deadline then",
    "    return cjson.encode({status='error', code='REDIS_ARGUMENT_INVALID'})",
    '  end',
    "  local values = redis.call('HMGET', keys[1], 'id', 'agentId', 'projectId', 'status')",
    '  if not values[1] or not values[2] or not values[3] or not values[4] or values[3] ~= args[1] then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    "  local current_deadline = redis.call('ZSCORE', keys[3], values[1])",
    '  if not current_deadline or tonumber(current_deadline) ~= expected_deadline then',
    "    return cjson.encode({status='unchanged'})",
    '  end',
    "  if values[4] == 'completed' or values[4] == 'disconnected' then",
    "    redis.call('ZREM', keys[3], values[1])",
    "    return cjson.encode({status='unchanged'})",
    '  end',
    "  local presence_ttl = redis.call('PTTL', keys[2])",
    '  if presence_ttl > 0 then',
    '    local clock = redis_now()',
    '    local reconciled_deadline = clock.milliseconds + presence_ttl',
    "    redis.call('ZADD', keys[3], reconciled_deadline, values[1])",
    "    return cjson.encode({status='reconciled', deadlineMs=reconciled_deadline})",
    '  end',
    '  if not stream_appendable(keys[4]) or not stream_appendable(keys[5]) then',
    "    return cjson.encode({status='error', code='REDIS_STATE_INVALID'})",
    '  end',
    '  local clock = redis_now()',
    "  redis.call('HSET', keys[1], 'status', 'disconnected')",
    "  redis.call('DEL', keys[2])",
    "  redis.call('ZREM', keys[3], values[1])",
    '  local event = {',
    "    id=args[3], version=1, type='session.disconnected', occurredAt=clock.timestamp,",
    '    workspaceId=args[2], projectId=values[3], agentId=values[2], sessionId=values[1],',
    "    payload={previousStatus=values[4], currentStatus='disconnected'}",
    '  }',
    '  local event_json = cjson.encode(event)',
    '  local streams = append_event(keys[4], keys[5], event_json)',
    "  return cjson.encode({status='disconnected', event=event, globalStreamId=streams.globalStreamId, projectStreamId=streams.projectStreamId})",
    'end',
    'local function not_implemented(keys, args)',
    "  return cjson.encode({status='not_implemented'})",
    'end',
    'local function library_version(keys, args)',
    `  return cjson.encode({version=${registry.version}, libraryName='${registry.libraryName}'})`,
    'end',
    register(registry.functions.projectRegister, 'project_register'),
    register(registry.functions.sessionRegister, 'session_register'),
    register(registry.functions.sessionHeartbeat, 'session_heartbeat'),
    register(registry.functions.sessionStatus, 'session_status'),
    register(registry.functions.sessionClose, 'session_close'),
    register(registry.functions.sessionDisconnect, 'session_disconnect'),
    register(registry.functions.version, 'library_version'),
    '',
  ].join('\n');

  return {
    registry,
    source,
    contentHash: createHash('sha256').update(source).digest('hex'),
  };
}
